run:
  dir: ../rethink_LOG/${hydra.job.name}__${hydra.job.override_dirname}
sweep:
  dir: ../rethink_LOG/${hydra.job.name}
  subdir: ${hydra.job.override_dirname}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  name: ${name}
  env_set:
    WANDB_API_KEY: "4631776b948ff1b794c99e015259b0812df58e59"
    CUDA_VISIBLE_DEVICES: "0"
  config:
    override_dirname:
      kv_sep: "_"
      item_sep: "__"'