

# output paths for hydra logs

run:
  dir: ${hydra.job.name}
sweep:
  dir: mulitrunX/
  subdir: ${hydra.job.name}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  name: ${log_dir}
  env_set:
    EXAMPLE_VAR: "example_value"
  config:
    override_dirname:
      kv_sep: "_"
      item_sep: "__"
