- "CenterEyeAnchor_pos_X"             #HMD
- "CenterEyeAnchor_pos_Y"
- "CenterEyeAnchor_pos_Z"
- "CenterEyeAnchor_euler_X"
- "CenterEyeAnchor_euler_Y"
- "CenterEyeAnchor_euler_Z"
- "LeftVirtualHand_pos_X"             #Left Hand
- "LeftVirtualHand_pos_Y"
- "LeftVirtualHand_pos_Z"
- "LeftControllerAnchor_euler_X"
- "LeftControllerAnchor_euler_Y"
- "LeftControllerAnchor_euler_Z"
- "RightVirtualHand_pos_X"            #Right Hand
- "RightVirtualHand_pos_Y"
- "RightVirtualHand_pos_Z"
- "RightControllerAnchor_euler_X"
- "RightControllerAnchor_euler_Y"
- "RightControllerAnchor_euler_Z"
