# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "tensorboard/"
  name: ${name}
  version: 0
  log_graph: False
  default_hp_metric: True
  prefix: ""
