# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${project_id}
  name: ${run_name}/${hydra:job.override_dirname}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # created dynamically with the help of status.json
  # entity: ""  # set to name of your wandb team or just remove it
  log_model: True
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
