# @package _global_

# specify here default training configuration
defaults:
#  - trainer: archery_bowling_trainer.yaml
#  - model: archery_bowling_model.yaml
#  - datamodule: archery_bowling_datamodule.yaml
#  - callbacks: my_wandb.yaml # set this to null if you don't want to use callbacks
#  - logger: wandb.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - random_test: random_test
  - experiment: null
  - hparams_search: null

  - hydra: rethink.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}
log_dir: ${work_dir}/../TF-LOG/${project_id}/${run_name}/

project_id: tensorflow-Lexion #"rethink_project_81"
run_name: ??? # "dummy_run_name_01"

batch_size: 64
IMAGE_SIZE: 224
N_CLASSES: 20 # TODO infer
LEARN_RATE: 0.001
INITIAL_EPOCHS: 5
FINE_TUNE_EPOCHS: 100
DROPOUT: 0.2
MODEL_HANDLE: 'https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4'


trainer: null
model: null
datamodule: null
callbacks: null
logger: null

# path to folder with data
data_dir: ${work_dir}/../DATA/Lexion-Images/

# use `python run.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python run.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False

# pretty print config at the start of the run using Rich library
print_config: False

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: True
